efzer_jobs_django/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.http import HttpResponseRedirect

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^jobs/', include('jobs.urls')),
    url(r'^$', lambda r: HttpResponseRedirect('jobs/')),
]

jobs/urls.py
from . import views
from django.conf.urls import url
from django.contrib.auth import views as auth_views

app_name = 'jobs'

urlpatterns = [
    url(r'^$', views.JobListView.as_view(), name='index'),
    url(r'^(?P<pk>[0-9]+)/$', views.JobDetailView.as_view(), name='detail'),
    url(r'^add/$', views.AddJobView.as_view(), name='add'),
    # url(r'^add\.do/$', views.add_job, name='action_add'),
    # url(r'^(?P<pk>[0-9]+)/update/$', views.UpdateJobView.as_view(), name='update'),
    # url(r'^(?P<pk>[0-9]+)/delete/$', views.DeleteJobView.as_view(), name='delete'),
    # url(r'^login/$', auth_views.login, {'template_name': 'jobs/login.html'}, name='login'),
    # url(r'^logout/$', auth_views.logout, name='logout'),
]

jobs/models.py
from django.core.exceptions import ValidationError
from django.db import models
from django.urls import reverse
from django.utils import timezone
from django.utils.encoding import python_2_unicode_compatible
from django.utils.translation import ugettext_lazy as _


def validate_class(grad_class):
    year_number = grad_class // 100
    class_number = grad_class % 100
    if not (100000 <= grad_class <= 999999):
        raise ValidationError(_('班级号应为6位整数'), params={'grad_class': grad_class})
    if year_number < 1958:
        raise ValidationError(_('毕业年份不合法'), params={'year_number': year_number})
    if class_number == 0:
        raise ValidationError(_('班级号不能为0'), params={'class_number': class_number})


@python_2_unicode_compatible
class Job(models.Model):

    class Meta:
        ordering = ['-date_published']
        verbose_name = _('职位')
        verbose_name_plural = _('职位')

    INTERN = 'INTERN'
    SOCIAL = 'SOCIAL'

    TYPE_CHOICES = [
        (INTERN, _('实习')),
        (SOCIAL, _('社招')),
    ]

    published = models.BooleanField(
        default=False,
        verbose_name=_('已发布')
    )

    date_published = models.DateTimeField(
        default=timezone.now,
        verbose_name=_('发布时间'),
        editable=False
    )

    times_viewed = models.IntegerField(
        default=0,
        verbose_name=_('已查看次数')
    )

    type = models.CharField(
        max_length=6,
        choices=TYPE_CHOICES,
        default=INTERN,
        verbose_name=_('招聘类型')
    )

    company = models.CharField(
        max_length=50,
        help_text=_('如 “Google” 或 “上海中学”'),
        verbose_name=_('单位名称')
    )

    location = models.CharField(
        max_length=50,
        help_text=_('如 “上海” 或 “Mountain View, CA”'),
        verbose_name=_('工作城市')
    )

    job_position = models.CharField(
        max_length=50,
        help_text=_('如 “软件工程师”'),
        verbose_name=_('招聘职位')
    )

    department = models.CharField(
        max_length=50,
        help_text=_('如 “人力资源部”'),
        verbose_name=_('工作部门')
    )

    publisher_class = models.SmallIntegerField(
        help_text=_('请填写六位班级号（四位毕业年份+两位班级号），如 “201602”'),
        default=195801,
        verbose_name=_('发布者班级'),
        validators=[validate_class]
    )

    publisher = models.CharField(
        max_length=50,
        help_text=_('请填写姓名'),
        verbose_name=_('发布者')
    )

    salary = models.CharField(
        max_length=50,
        help_text=_('如 “10000元/月”'),
        verbose_name=_('薪资')
    )

    submitting_resume = models.CharField(
        max_length=300,
        help_text='如 “发送简历至 hr@google.com”',
        verbose_name=_('简历递交方式')
    )

    description = models.CharField(
        max_length=300,
        blank=True,
        verbose_name=_('工作描述')
    )

    requirements = models.CharField(
        max_length=300,
        blank=True,
        verbose_name=_('招聘要求')
    )

    company_description = models.CharField(
        max_length=2000,
        blank=True,
        verbose_name=_('单位介绍')
    )

    def __str__(self):
        return self.job_position + " at " + self.department + ", " + self.company + " in " + self.location

    def get_absolute_url(self):
        return reverse('jobs:detail', kwargs={'pk': self.pk})

    def get_publisher_grad_year(self):
        return self.publisher_class // 100

    def get_publisher_grad_class(self):
        return self.publisher_class % 100

jobs/forms.py
from django.forms import ModelForm
from django.forms.widgets import Input, Textarea, RadioSelect
from django.utils.translation import ugettext as _
from jobs.models import Job


class JobForm(ModelForm):
    class Meta:
        model = Job
        fields = [
            'type',
            'company',
            'location',
            'job_position',
            'department',
            'publisher_class',
            'publisher',
            'salary',
            'submitting_resume',
            'description',
            'requirements',
            'company_description'
        ]

        widgets = {
            'type': RadioSelect(attrs={'class': "mdc-radio__native-control", 'required': True}),
            'company': Input(attrs={'class': "mdc-textfield__input", 'required': True}),
            'location': Input(attrs={'class': "mdc-textfield__input", 'required': True}),
            'job_position': Input(attrs={'class': "mdc-textfield__input", 'required': True}),
            'department': Input(attrs={'class': "mdc-textfield__input", 'required': True}),
            'publisher_class': Input(attrs={'class': "mdc-textfield__input", 'required': True}),
            'publisher': Input(attrs={'class': "mdc-textfield__input", 'required': True}),
            'salary': Input(attrs={'class': "mdc-textfield__input", 'required': True}),
            'submitting_resume': Input(attrs={'class': "mdc-textfield__input", 'required': True}),
            'description': Textarea(attrs={'rows': 8, 'class': "mdc-textfield__input"}),
            'requirements': Textarea(attrs={'rows': 8, 'class': "mdc-textfield__input"}),
            'company_description': Textarea(attrs={'rows': 12, 'class': "mdc-textfield__input"}),
        }

        labels = {
            'type': _('招聘类型'),
            'company': _('单位名称'),
            'location': _('工作城市'),
            'job_position': _('工作职位'),
            'department': _('工作部门'),
            'publisher_class': _('发布者班级'),
            'publisher': _('发布者'),
            'salary': _('薪资'),
            'submitting_resume': _('简历投递方式'),
            'description': _('工作描述'),
            'requirements': _('招聘要求'),
            'company_description': _('单位介绍'),
        }

jobs/views.py
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse_lazy
from django.views import generic
from django.utils.translation import ugettext as _

from jobs.forms import JobForm
from jobs.models import Job


class JobListView(generic.ListView):
    template_name = 'jobs/index.html'
    context_object_name = 'job_list'

    def get_queryset(self):
        return Job.objects.filter(published=True).order_by('-date_published')


class JobDetailView(generic.DetailView):
    model = Job
    template_name = 'jobs/detail.html'
    queryset = Job.objects.filter(published=True)

    def get_queryset(self):
        return Job.objects.filter(published=True)

    def get_object(self, queryset=queryset):
        job = super(JobDetailView, self).get_object()
        job.times_viewed += 1
        job.save()
        return job


class AddJobView(SuccessMessageMixin, generic.CreateView):
    model = Job
    form_class = JobForm
    success_url = reverse_lazy('jobs:index')
    success_message = _('申请已提交，审核后将发布到主页')


class UpdateJobView(generic.UpdateView):
    model = Job
    form_class = JobForm


class DeleteJobView(generic.DeleteView):
    model = Job
    success_url = reverse_lazy('jobs:index')

jobs/templates/jobs/base.html
{% load static %}
{% load i18n %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link rel="stylesheet" href="{% static 'material-icons.css' %}">
    <link rel="stylesheet" href="{% static 'efz-icon.css' %}">

    <link rel="stylesheet" href="https://unpkg.com/material-components-web@latest/dist/material-components-web.min.css">
    <link rel="stylesheet" href="{% static 'style.css' %}"/>

    <title>EFZer Jobs</title>

</head>

<body class="mdc-typography">

{% block navbar %}

<header class="mdc-toolbar mdc-elevation--z8">
    <div class="mdc-toolbar__row">
        <section class="mdc-toolbar__section mdc-toolbar__section--align-start">
            <a href="/jobs" class="material-icons mdc-toolbar__icon--menu"><i class="icon-efz"></i></a>

            <span class="mdc-toolbar__title" onclick="window.location='{% url 'jobs:index' %}'">EFZer 校友招</span>
        </section>
        <section class="mdc-toolbar__section mdc-toolbar__section--align-end" role="toolbar">
            {% block toolbar %}

            {% endblock %}
        </section>
    </div>
</header>

{% endblock %}

<main>
        <div class="container">
            {% block content %}


            {% endblock %}
        </div>
</main>

<script src="https://unpkg.com/material-components-web@latest/dist/material-components-web.min.js"></script>

{% block script %}

{% endblock %}

<script>
    (function(global) {
        [].forEach.call(document.querySelectorAll('.mdc-ripple-surface:not([data-demo-no-js])'), function(surface) {
            mdc.ripple.MDCRipple.attachTo(surface);
        });
    })(this);
</script>
<script>window.mdc.autoInit();</script>
</body>
</html>

jobs/templates/jobs/detail.html
{% extends 'jobs/base.html' %}
{% load i18n %}
{% block toolbar %}
{#          <a href="{% url 'jobs:update' job.id %}" class="material-icons mdc-toolbar__icon" aria-label="Edit" alt="Edit">mode_edit</a>#}
{#          <a href="{% url 'jobs:delete' job.id %}" class="material-icons mdc-toolbar__icon" aria-label="Delete" alt="Delete">delete</a>#}
{% endblock %}


{% block content %}
    <div class="job-card job-card-more mdc-card">
        <div class="mdc-card__media">
            <h2 class="mdc-card__title mdc-card__title--large"> {{ job.company }} {{ job.job_position }} </h2>
        </div>
        <div class="mdc-card__supporting-text">
            <p>
                <span class="job-prop"> <i class="material-icons">pin_drop</i> {{ job.location }} </span>
                <span class="job-prop"> <i class="material-icons">perm_contact_calendar</i> {{ job.get_type_display }} </span>
                <span class="job-prop"> <i class="material-icons">domain</i> {{ job.department }} </span>
                <span class="job-prop"> <i class="material-icons">payment</i> {{ job.salary }} </span></p>
            <p>
                <span class="job-prop"> <i class="material-icons">remove_red_eye</i> 已被查看 {{ job.times_viewed }} 次 </span>
            </p>
            <p>
                <span class="job-prop"> <i class="material-icons">schedule</i>
                    由 {{ job.get_publisher_grad_year }}届{{ job.get_publisher_grad_class }}班{{ job.publisher }} 发布于 {{ job.date_published.date }}
                </span>
            </p>
        </div>
    </div>

    {#    <div class="mdl-card__menu">#}
    {#        <button class="mdl-button mdl-button--icon mdl-js-button mdl-js-ripple-effect">#}
    {#            <i class="material-icons">share</i>#}
    {#        </button>#}
    {#    </div>#}

    <div class="job-detail-card mdc-card">

        <div class="mdc-card__primary">
            <h1 class="mdc-card__title mdc-card__title--large">简历投递方式</h1>
        </div>

        <div class="job-detail-text mdc-card__supporting-text">
            <p>{{ job.submitting_resume }}</p>
        </div>

    </div>

    {% if job.description != "" %}
        <div class="job-detail-card mdc-card">
            <div class="mdc-card__primary">
                <h1 class="mdc-card__title mdc-card__title--large">工作详情</h1>
            </div>
            <div class="job-detail-text mdc-card__supporting-text">
                <p>{{ job.description }}</p>
            </div>

        </div>
    {% endif %}

    {% if job.requirements != "" %}
        <div class="job-detail-card mdc-card">
            <div class="mdc-card__primary">
                <h1 class="mdc-card__title mdc-card__title--large">工作要求</h1>
            </div>

            <div class="job-detail-text mdc-card__supporting-text">
                <p>{{ job.requirements }}</p>
            </div>
        </div>
    {% endif %}

    {% if job.company_description != "" %}
        <div class="job-detail-card mdc-card">
            <div class="mdc-card__primary">
                <h1 class="mdc-card__title mdc-card__title--large">公司介绍</h1>
            </div>

            <div class="job-detail-text mdc-card__supporting-text">
                <p>{{ job.company_description }}</p>
            </div>
        </div>
    {% endif %}
{% endblock %}

jobs/templates/jobs/index.html
{% extends 'jobs/base.html' %}
{% load i18n %}
{% block toolbar %}
    <a href="{% url 'jobs:add' %}" class="material-icons mdc-toolbar__icon" aria-label="Add" alt="Add">add</a>
    <a id="menu-search" href="#" class="material-icons mdc-toolbar__icon" aria-label="Search" alt="Search">search</a>
{% endblock %}


{% block content %}

    {% if job_list %}
        {% for job in job_list %}
            <div class="job-card mdc-card" onclick="window.location='{% url 'jobs:detail' job.id %}';">
                <div class="mdc-card__media">
                    <h1 class="mdc-card__title mdc-card__title--large">{{ job.company }} {{ job.job_position }}</h1>
                </div>
{#                <div class="mdl-card__title">#}
{#                    <h2 class="mdl-card__title-text"> {{ job.company }} </h2>#}
{#                </div>#}
                <div class="mdc-card__supporting-text">
                    <p>
                        <span class="job-prop"> <i class="material-icons">pin_drop</i> {{ job.location }} </span>
{#                        <span class="job-prop"> <i class="material-icons">work</i> {{ job.job_position }} </span>#}
                        <span class="job-prop"> <i class="material-icons">perm_contact_calendar</i> {{ job.get_type_display }} </span>
                        <span class="job-prop"> <i class="material-icons">domain</i> {{ job.department }} </span>
                        <span class="job-prop"> <i class="material-icons">payment</i> {{ job.salary }} </span>
                    </p>
                </div>
{#                <div class="mdl-card__menu">#}
{#                    <button class="mdl-button mdl-button--icon mdl-js-button mdl-js-ripple-effect">#}
{#                        <i class="material-icons">share</i>#}
{#                    </button>#}
{#                </div>#}
            </div>
        {% endfor %}
    {% else %}
        <div class="no-job-card mdc-card">
            <div class="mdc-card__primary">
                <h2 class="mdc-card__title mdc-card__title--large"> {% trans "暂无招聘信息。" %} </h2>
            </div>
        </div>
    {% endif %}
{#    <button class="mdc-fab material-icons" onclick="window.location='{% url 'jobs:add' %}'" aria-label="Add">#}
{#        <span class="mdc-fab__icon">#}
{#            add#}
{#        </span>#}
{#    </button>#}

    <div id="mdc-js-snackbar" class="mdc-snackbar" aria-live="assertive" aria-atomic="true" aria-hidden="true">
        <div class="mdc-snackbar__text">Message</div>
        <div class="mdc-snackbar__action-wrapper">
            <button type="button" class="mdc-button mdc-snackbar__action-button"></button>
        </div>
    </div>

    {% for message in messages %}
        <div id="add-success-message-snackbar" class="mdc-snackbar" aria-live="assertive" aria-atomic="true" aria-hidden="true">
            <div class="mdc-snackbar__text">{{ message }}</div>
            <div class="mdc-snackbar__action-wrapper">
                <button type="button" class="mdc-button mdc-snackbar__action-button">OK</button>
            </div>
        </div>
    {% endfor %}

{% endblock %}

{% block script %}
<script>
      (function(global) {
          'use strict';
          var MDCSnackbar = global.mdc.snackbar.MDCSnackbar;
          var messageSnackbar = document.getElementById('add-success-message-snackbar');
          if (messageSnackbar) {
              var snackbar = new MDCSnackbar(messageSnackbar);
              snackbar.show({
                  message: "添加成功，等待审核。",
                  actionOnBottom: false,
                  multiline: false,
                  actionText: "快点",
                  timeout: 2000,
                  actionHandler: function () {
                      console.log("知道嘞，别催")
                  }
              });
          }
      })(this);
</script>
{% endblock %}

jobs/templates/jobs/job_confirm_delete.html
{% extends 'jobs/base.html' %}

{% block content %}

    <div class="delete-confirm-card mdc-card">
        <div class="mdc-card__primary">
            <h2 class="mdc-card__title mdc-card__title--large"> 确认删除{{ job.company }}？ </h2>
        </div>
        <section class="mdc-card__actions">
            <form action="" method="post">{% csrf_token %}
                <button type="submit" class="mdc-button mdc-button--raised mdc-button--compact mdc-card__action">确认</button>
                <button onclick="window.history.back()" class="mdc-button mdc-button--compact mdc-card__action">取消</button>
            </form>
        </section>
    </div>

{% endblock %}

jobs/templates/jobs/job_form.html
{% extends 'jobs/base.html' %}


{% block content %}

<div class="add-job-panel mdc-card">
    <div class="mdc-card__primary">
        <h1 class="mdc-card__title mdc-card__title--large">添加职位信息</h1>
    </div>
    <div class="add-job-form">
        <form name="add-job-form" action="" method="post">
            {% csrf_token %}
            {% for field in form %}
                    {% if field.name == "type" %}
                        {% for choice in field %}
                            <div class="mdc-form-field">
                                <div class="mdc-radio">
                                    {{ choice.tag }}
                                    <div class="mdc-radio__background">
                                        <div class="mdc-radio__outer-circle"></div>
                                        <div class="mdc-radio__inner-circle"></div>
                                    </div>
                                </div>
                                <label for="{{ choice.id_for_label }}" id="{{ choice.id_for_label }}-label">{{ choice.choice_label }}</label>
                            </div>
                        {% endfor %}
                    {% else %}
                        <div class="mdc-textfield {% if field.errors %}mdc-textfield--invalid{% endif %}{% if field.name == "description" or field.name == "requirements" or field.name == "company_description"%}mdc-textfield--multiline{% endif %} mdc-textfield--upgraded" data-mdc-auto-init="MDCTextfield">
                            {{ field }}
                            <label class="mdc-textfield__label" for="id_{{ field.name }}">{{ field.label }}</label>
                        </div>
                        {% if field.errors %}
                            {% for error in field.errors %}
                                <p class="mdc-textfield-helptext mdc-textfield-helptext--validation-msg" style="display: block;" aria-hidden="false">
                                    {{ error }}
                                </p>
                            {% endfor %}
                        {% else %}
                            {% if field.help_text %}
                            <p class="mdc-textfield-helptext" aria-hidden="true">
                                {{ field.help_text }}
                            </p>
                                {% endif %}
                        {% endif %}
                    {% endif %}
            {% endfor %}

            <button type="submit" class="mdc-fab material-icons" aria-label="Submit">
                <span class="mdc-fab__icon">send</span>
            </button>

        </form>
    </div>
</div>

{% endblock %}

{% block script %}
    {{ block.super }}
    <script>
      (function(global) {
        'use strict';
        var MDCFormField = global.mdc.formField.MDCFormField;
        var MDCRadio = global.mdc.radio.MDCRadio;

        var formFields = document.querySelectorAll('.mdc-form-field');
        for (var i = 0, formField; formField = formFields[i]; i++) {
          var formFieldInstance = new MDCFormField(formField);

          var radio = formField.querySelector('.mdc-radio:not([data-demo-no-js])');
          if (radio) {
            var radioInstance = new MDCRadio(radio);
            formFieldInstance.input = radioInstance;
          }
        }
      })(this);
    </script>
{% endblock %}

jobs/templates/jobs/login.html
{% extends 'jobs/base.html' %}

{% block content %}
<div class="login-panel mdc-card">
    <div class="mdc-card__primary">
        <h1 class="mdc-card__title mdc-card__title--large">登录</h1>
    </div>
    <div class="login-form">
        <form action="{% url 'jobs:login' %}" method="post">
            {% csrf_token %}
            <div class="mdc-textfield mdc-textfield--upgraded" data-mdc-auto-init="MDCTextfield">
                <input required class="mdc-textfield__input" type="text" id="company" name="company"/>
                <label class="mdc-textfield__label" for="company">用户名</label>
            </div>
            <div class="mdc-textfield mdc-textfield--upgraded" data-mdc-auto-init="MDCTextfield">
                <input required class="mdc-textfield__input" type="password" id="location" name="location"/>
                <label class="mdc-textfield__label" for="location">密码</label>
            </div>
                <button class="mdc-fab material-icons" type="submit" aria-label="Login">
                    <span class="mdc-fab__icon">
                        send
                    </span>
                </button>
        </form>
    </div>
</div>
{% endblock %}